### ISSUE TITLE
Pre-release from feature branch

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/PCAP-core#9]
mismatchQC + fragment testing
Depends on

- [x] #5 `feature/rg_metadata`
- [x] #6 `feature/rg_metadata`
- [x] #7 `feature/mismatchQc_C`
- [x] #8 `feature/bamstats_qcfail`
- [x] Merge any features into `feature/mismatchQc_C`
- [ ] Add ability to request `.csi` indexing of BAM
- [ ] Create pre-release from `feature/mismatchQc_C`

**Comment by keiranmraine** [comment]
Depends on #6, #7, #8

**Comment by keiranmraine** [comment]
4.1.0-rc1 created
